version: '2.1'
services:
  live-reload:
    image: spotfy-radio
    build: .
    environment:
      PORT: 3000
    command: 
      - npm
      - rum
      - live-reload
    volumes:
      - .:/home/node/spotfy-radio/
      - node_modules:/home/node/spotfy-radio/node_modules
    ports:
      - 3000:3000
volumes:
  node_modules: {}